///***///***///---\\\***\\\***\\\___///***___***\\\___///***///***///---\\\***\\\***///
// Файл грамматики языка. Английские ключевые слова.
//
// Версия: 1.0.0.1
// Дата последнего изменения: 14:53 30.01.2023
// 
// Автор: Маслов А.С. (https://github.com/ArtemMaslov).
///***///***///---\\\***\\\***\\\___///***___***\\\___///***///***///---\\\***\\\***///

GRAMMAR(Keyword, English, If, "if")

GRAMMAR(Keyword, English, Else, "else")

GRAMMAR(Keyword, English, While, "while")

GRAMMAR(Keyword, English, Return, "ret")

GRAMMAR(Keyword, English, Input, "in")

GRAMMAR(Keyword, English, Output, "out")