
GRAMMAR(LngTokenType::Keyword, GrammarType::English, KeywordType::If, "if")

GRAMMAR(LngTokenType::Keyword, GrammarType::English, KeywordType::Else, "else")

GRAMMAR(LngTokenType::Keyword, GrammarType::English, KeywordType::While, "while")

GRAMMAR(LngTokenType::Keyword, GrammarType::English, KeywordType::Return, "ret")

GRAMMAR(LngTokenType::Keyword, GrammarType::English, KeywordType::Input, "in")

GRAMMAR(LngTokenType::Keyword, GrammarType::English, KeywordType::Output, "out")