
GRAMMAR(LngTokenType::Operator, GrammarType::Universal, OperatorType::Addition, "+")

GRAMMAR(LngTokenType::Operator, GrammarType::Universal, OperatorType::Subtraction, "-")

GRAMMAR(LngTokenType::Operator, GrammarType::Universal, OperatorType::Multiplication, "*")

GRAMMAR(LngTokenType::Operator, GrammarType::Universal, OperatorType::Division, "/")

GRAMMAR(LngTokenType::Operator, GrammarType::Universal, OperatorType::Equal, "==")

GRAMMAR(LngTokenType::Operator, GrammarType::Universal, OperatorType::NotEqual, "!=")

GRAMMAR(LngTokenType::Operator, GrammarType::Universal, OperatorType::GreaterEqual, ">=")

GRAMMAR(LngTokenType::Operator, GrammarType::Universal, OperatorType::Greater, ">")

GRAMMAR(LngTokenType::Operator, GrammarType::Universal, OperatorType::LessEqual, "<=")

GRAMMAR(LngTokenType::Operator, GrammarType::Universal, OperatorType::Less, "<")

GRAMMAR(LngTokenType::Operator, GrammarType::Universal, OperatorType::Not, "!")

GRAMMAR(LngTokenType::Operator, GrammarType::Universal, OperatorType::And, "&&")

GRAMMAR(LngTokenType::Operator, GrammarType::Universal, OperatorType::Or, "||")

GRAMMAR(LngTokenType::Operator, GrammarType::Universal, OperatorType::SetValue, "=")
