///***///***///---\\\***\\\***\\\___///***___***\\\___///***///***///---\\\***\\\***///
// Файл грамматики языка. Операторы, общие для всех грамматик.
//
// Версия: 1.0.0.1
// Дата последнего изменения: 14:53 30.01.2023
// 
// Автор: Маслов А.С. (https://github.com/ArtemMaslov).
///***///***///---\\\***\\\***\\\___///***___***\\\___///***///***///---\\\***\\\***///

GRAMMAR(Operator, Universal, Addition, "+", "+")

GRAMMAR(Operator, Universal, Subtraction, "-", "-")

GRAMMAR(Operator, Universal, Multiplication, "*", "*")

GRAMMAR(Operator, Universal, Division, "/", "/")

GRAMMAR(Operator, Universal, Equal, "==", "==")

GRAMMAR(Operator, Universal, NotEqual, "!=", "!=")

GRAMMAR(Operator, Universal, GreaterEqual, ">=", "&gt;=")

GRAMMAR(Operator, Universal, Greater, ">", "&gt;=")

GRAMMAR(Operator, Universal, LessEqual, "<=", "&lt;=")

GRAMMAR(Operator, Universal, Less, "<", "&lt;")

GRAMMAR(Operator, Universal, Not, "!", "!")

GRAMMAR(Operator, Universal, And, "&&", "&&")

GRAMMAR(Operator, Universal, Or, "||", "||")

GRAMMAR(Operator, Universal, SetValue, "=", "=")
