
GRAMMAR(LngTokenType::SpecialSymbol, GrammarType::Universal, SpecialSymbolType::OpeningParenthesis, "(")

GRAMMAR(LngTokenType::SpecialSymbol, GrammarType::Universal, SpecialSymbolType::ClosingParenthesis, ")")

GRAMMAR(LngTokenType::SpecialSymbol, GrammarType::Universal, SpecialSymbolType::OpeningSquareBracket, "[")

GRAMMAR(LngTokenType::SpecialSymbol, GrammarType::Universal, SpecialSymbolType::ClosingSquareBracket, "]")

GRAMMAR(LngTokenType::SpecialSymbol, GrammarType::Universal, SpecialSymbolType::OpeningBrace, "{")

GRAMMAR(LngTokenType::SpecialSymbol, GrammarType::Universal, SpecialSymbolType::ClosingBrace, "}")

GRAMMAR(LngTokenType::SpecialSymbol, GrammarType::Universal, SpecialSymbolType::Point, ".")

GRAMMAR(LngTokenType::SpecialSymbol, GrammarType::Universal, SpecialSymbolType::Comma, ",")

//GRAMMAR(LngTokenType::SpecialSymbol, GrammarType::Universal, SpecialSymbolType::Equal, "=")

GRAMMAR(LngTokenType::SpecialSymbol, GrammarType::Universal, SpecialSymbolType::Colon, ":")

GRAMMAR(LngTokenType::SpecialSymbol, GrammarType::Universal, SpecialSymbolType::Semicolon, ";")

GRAMMAR(LngTokenType::SpecialSymbol, GrammarType::Universal, SpecialSymbolType::SingleQuotes, "\'")

GRAMMAR(LngTokenType::SpecialSymbol, GrammarType::Universal, SpecialSymbolType::DoubleQuotes, "\"")
