///***///***///---\\\***\\\***\\\___///***___***\\\___///***///***///---\\\***\\\***///
// Файл грамматики языка. Специальные символы, общие для всех грамматик.
//
// Версия: 1.0.0.1
// Дата последнего изменения: 14:53 30.01.2023
// 
// Автор: Маслов А.С. (https://github.com/ArtemMaslov).
///***///***///---\\\***\\\***\\\___///***___***\\\___///***///***///---\\\***\\\***///

GRAMMAR(SpecialSymbol, Universal, OpeningParenthesis, "(")

GRAMMAR(SpecialSymbol, Universal, ClosingParenthesis, ")")

GRAMMAR(SpecialSymbol, Universal, OpeningSquareBracket, "[")

GRAMMAR(SpecialSymbol, Universal, ClosingSquareBracket, "]")

GRAMMAR(SpecialSymbol, Universal, OpeningBrace, "{")

GRAMMAR(SpecialSymbol, Universal, ClosingBrace, "}")

GRAMMAR(SpecialSymbol, Universal, Point, ".")

GRAMMAR(SpecialSymbol, Universal, Comma, ",")

//GRAMMAR(SpecialSymbol, Universal, Equal, "=")

GRAMMAR(SpecialSymbol, Universal, Colon, ":")

GRAMMAR(SpecialSymbol, Universal, Semicolon, ";")

GRAMMAR(SpecialSymbol, Universal, SingleQuotes, "\'")

GRAMMAR(SpecialSymbol, Universal, DoubleQuotes, "\"")